# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dongwei Xu
tagline:          ''
description:      'PhD candidate in Economics at Boston University'
url:              http://dongweix.github.io

# Author
author:
  name:           'Dongwei Xu'
  url:            http://dongweix.github.io

paginate:         5

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
