# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dongwei Xu
tagline:          'Welcome'
description:      'Ph.D. candidate in Economics at Boston University'
url:              http://dongweix.github.io
baseurl:          /

# Author
author:
  name:           'Dongwei Xu'
  url:            http://dongweix.github.io

# Posts Max
paginate:         5

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
exclude:
  - CNAME
  - LICENSE
  - README
  - Gemfile
  - Gemfile.lock
  - draft/
